name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
  packages: write
  security-events: write
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup tools
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - uses: actions/setup-go@v5
        with: { go-version: '1.22' }

      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Cache go
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}

      - name: Pre-commit (lint)
        uses: pre-commit/action@v3.0.1

      - name: Unit tests (multi-lang)
        run: ./scripts/run-tests.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: EnmanuelMejia
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push service images (amd64)
        run: ./scripts/push-images.sh
