name: Helm-OCI-Release
on:
  push:
    branches: [ "main" ]
    paths:
      - "helm/**"
permissions:
  packages: write
  contents: read
jobs:
  helm_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: GHCR login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u EnmanuelMejia --password-stdin
      - name: Package & push umbrella
        working-directory: helm/superlab-umbrella
        run: |
          helm dependency build
          helm package .
          CHART=$(ls *.tgz)
          helm push "$CHART" oci://ghcr.io/EnmanuelMejia
