name: Kustomize-Validate
on:
  pull_request:
    branches: [ main ]
jobs:
  kustomize-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: kustomize dev
        run: kubectl kustomize kustomize/overlays/dev | kubeconform -strict -ignore-missing-schemas -summary
      - name: kustomize stage
        run: kubectl kustomize kustomize/overlays/stage | kubeconform -strict -ignore-missing-schemas -summary
      - name: kustomize prod
        run: kubectl kustomize kustomize/overlays/prod | kubeconform -strict -ignore-missing-schemas -summary
    env:
      KUBECONFORM_VERSION: v0.6.7
    # install kubeconform & kubectl (standalone)
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Install kubectl
        run: |
          curl -sLO https://dl.k8s.io/release/$(curl -sL https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
      - name: Install kubeconform
        run: |
          curl -sL https://github.com/yannh/kubeconform/releases/download/${KUBECONFORM_VERSION}/kubeconform-linux-amd64.tar.gz | sudo tar -xz -C /usr/local/bin kubeconform
      - name: Validate dev
        run: kubectl kustomize kustomize/overlays/dev | kubeconform -strict -ignore-missing-schemas -summary
      - name: Validate stage
        run: kubectl kustomize kustomize/overlays/stage | kubeconform -strict -ignore-missing-schemas -summary
      - name: Validate prod
        run: kubectl kustomize kustomize/overlays/prod | kubeconform -strict -ignore-missing-schemas -summary
