name: Security-Scans
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "17 3 * * *"
permissions:
  contents: read
  security-events: write
  packages: read
jobs:
  trivy-fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-fs.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy-fs.sarif }
  trivy-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: config
          ignore-unfixed: true
          format: sarif
          output: trivy-config.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy-config.sarif }
  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          soft_fail: true
